security:
    providers:
        jwt:
            lexik_jwt:
                class: App\Entity\User
    
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/api/login
            stateless: true
            json_login:
                check_path: /api/login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        
        api:
            pattern: ^/api
            stateless: true
            jwt: ~
            custom_authenticator: App\Security\JWTAuthenticator

        main:
            pattern: ^/
            stateless: false
            jwt:
                provider: jwt

            logout:
                path: app_logout

    access_control:
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/logout, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/register, roles: PUBLIC_ACCESS }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/users/admin, roles: ROLE_ADMIN }
        - { path: ^/api/users, roles: ROLE_USER }
