version: '3.8'

services:
  php:
    image: dunglas/symfony-docker
    container_name: symfony_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      DATABASE_URL: mysql://root:root@mysql:3306/symfony

  mysql:
    image: mysql:8.0
    container_name: symfony_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
